### ISSUE TITLE
Readme references the wrong url

### ISSUE THREAD

**Issue by nickfaasen** [limbic/Security101forSMBs#1]
Hi Jonathan,

Great session today. Started reading Security 101 for SMBs and noticed the url behind https://www.haveibeenpwnd.com/ isn't correct. It's referencing https://www.haveibeenpownd.com/ but should be http://haveibeenpwned.com/. Guess this is not a 50k 'bug' found but hope this helps the cause! 

Kind regards,
Nick

**Comment by limbic** [comment]
Thank you @nickfaasen! Fixed.

**Comment by nickfaasen** [comment]
Hi Jonathan,

Still the wrong url. Should be: https://www.haveibeenpwn**e**d.com/.

Kind regards,
Nick

**Comment by limbic** [comment]
Really fixed now! Thank you.
